title: Rambling
name: Rambling
author: JP Lacy
email: lacyjpr@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
Travels and tribulations of a rambling meandering old man

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
